#!/usr/bin/env python

import rospy
import moveit_commander
import moveit_msgs.msg
import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from nav_msgs.msg import OccupancyGrid


class explore:

    def __init__(self):
        '''
        Initilization function.
        '''






if __name__== "__main__":
    explore()
    rospy.spin()